apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-frontend-deployment.yaml
- ./coit-frontend-service-lb
images:
- name: coitlearning/coit-frontend
  newTag: latest

namePrefix: frontend-
nameSuffix: -development

commonLabels:
  customer: customer1
  myapp: coit-frontend
  app: coitfrontend
  managed-by: kustomize
  
secretGenerator:
  - name: coit-frontend-secrets
    envs:
    - applicationsecrets.properties


